env: "local"

spotify_client_id: "e846fad163144ec69ab48ca8fc73d192"
spotify_client_secret: "c7626ca759aa4f898cc91733e13dfcce"

database:
    host: "spotifysorter-mysql-1"
    port: "3306"
    user: "root"
    password: "root"
    database: "spotify_db"

http_server:
  address: "0.0.0.0:8080"
  timeout: 5s
  idle_timeout: 60s